export const titles = {
    HEADER_MAIN_TITLE: 'Баю-Бай',
    HEADER_TEXT_MAIN_SCREEN: 'Тихая музыка',
    HEADER_CREATE_NEW_SOUND: 'Создание звука',
    HEADER_SOUND: 'Звук',
    MusicListTab_TITLE_ONE: 'ДОМАШНЕЕ',
    MusicListTab_TITLE_TWO: 'ЛУЧШЕЕ ДЛЯ НОВОРОЖДЕННЫХ',
    TITLE_TWO_TEXT_1: 'Лоно матери',
    TITLE_TWO_TEXT_2: 'Пылесос',
    TITLE_TWO_TEXT_3: 'Фен',
    TITLE_TWO_TEXT_4: 'Шшшш',
    TITLE_TWO_TEXT_5: 'Шшшш, Шшшш, Шшшш',
    MusicListTab_TITLE_THREE: 'ЛУЧШЕЕ ДЛЯ МЛАДЕНЦЕВ',
    TITLE_THREE_TEXT_1: 'Автомобиль',
    TITLE_THREE_TEXT_2: 'Вентилятор',
    TITLE_THREE_TEXT_3: 'Горная Река',
    TITLE_THREE_TEXT_4: 'Дождь',
    MusicListTab_TITLE_FOUR: 'ЛУЧШЕЕ ДЛЯ РОДИТЕЛЕЙ',
    TITLE_FOUR_TEXT_1: 'Гроза',
    TITLE_FOUR_TEXT_2: 'Журчащий Ручей',
    TITLE_FOUR_TEXT_3: 'Звуки Побережья',
    TITLE_FOUR_TEXT_4: 'Треск Камина',
    TEXT_INPUT: 'Имя звука',
    DURATION_TEXT: 'Продолжительность: ',
    VOLUME_TEXT: 'Громкость: ',
    SLEPPER_TRACKER: 'Отслеживание сна: ',
    TURN_ON: 'Вкл',
    TURN_OFF: 'Выкл',
    LONG_TEXT: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    REGISTRATION_TITLE: 'Регистрация',
    REGISTRATION_LOGIN: 'Логин',
    REGISTRATION_TYPE_LOGIN: 'Введите логин',
    REGISTRATION_PASSWORD: 'Пароль',
    REGISTRATION_TYPE_PASSWORD: 'Введите пароль',
    LOGIN_BTN: 'Войти',
    HAVE_NOT_ACCOUNT: 'Еще нет аккаунта?',
    HAVE_ACCOUNT: 'Уже зарегистрированы?',
    INFO_HEADER_TEXT_TITLE: 'NEWBORNS & BABIES',
    INFO_HEADER_TEXT_TITLE_TWO: 'Parenting',
    INFO_TITLE_ONE: 'Baby Care 101',
    INFO_SUBTITLE_ONE: 'Dr. Harver Karp, Dr. Delaney Gracy, Corky Harvey IBCLC and more',
    INFO_TITLE_TWO: 'Caring For Your Newborn',
    INFO_SUBTITLE_TWO: 'Dr. Sema Hart and Prof. Jim Coffey',
    INFO_TITLE_THREE: 'Caring For Your Newborn',
    INFO_SUBTITLE_THREE: 'Dr, Glenn I.Latham, Utah State University',
    INFO_HEADER_FREE: 'FREE',


}

