export const titles = {
  HEADER_MAIN_TITLE: 'Баю-Бай',
  HEADER_TEXT_MAIN_SCREEN: 'Тихая музыка',
  HEADER_CREATE_NEW_SOUND: 'Создание звука',
  HEADER_SOUND: 'Звук',
  MusicListTab_TITLE_ONE: 'ДОМАШНЕЕ',
  MusicListTab_TITLE_TWO: 'ЛУЧШЕЕ ДЛЯ НОВОРОЖДЕННЫХ',
  TITLE_TWO_TEXT_1: 'Лоно матери',
  TITLE_TWO_TEXT_2: 'Пылесос',
  TITLE_TWO_TEXT_3: 'Фен',
  TITLE_TWO_TEXT_4: 'Шшшш',
  TITLE_TWO_TEXT_5: 'Шшшш, Шшшш, Шшшш',
  MusicListTab_TITLE_THREE: 'ЛУЧШЕЕ ДЛЯ МЛАДЕНЦЕВ',
  TITLE_THREE_TEXT_1: 'Автомобиль',
  TITLE_THREE_TEXT_2: 'Вентилятор',
  TITLE_THREE_TEXT_3: 'Горная Река',
  TITLE_THREE_TEXT_4: 'Дождь',
  MusicListTab_TITLE_FOUR: 'ЛУЧШЕЕ ДЛЯ РОДИТЕЛЕЙ',
  TITLE_FOUR_TEXT_1: 'Гроза',
  TITLE_FOUR_TEXT_2: 'Журчащий Ручей',
  TITLE_FOUR_TEXT_3: 'Звуки Побережья',
  TITLE_FOUR_TEXT_4: 'Треск Камина',
  TEXT_INPUT: 'Имя звука',
  DURATION_TEXT: 'Продолжительность: ',
  VOLUME_TEXT: 'Громкость: ',
  SLEPPER_TRACKER: 'Отслеживание сна: ',
  TURN_ON: 'Вкл',
  TURN_OFF: 'Выкл',
  LONG_TEXT:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  REGISTRATION_TITLE: 'Регистрация',
  REGISTRATION_LOGIN: 'Логин',
  REGISTRATION_TYPE_LOGIN: 'Введите логин',
  REGISTRATION_PASSWORD: 'Пароль',
  REGISTRATION_TYPE_PASSWORD: 'Введите пароль',
  LOGIN_BTN: 'Войти',
  HAVE_NOT_ACCOUNT: 'Еще нет аккаунта?',
  HAVE_ACCOUNT: 'Уже зарегистрированы?',
  INFO_HEADER_TEXT_TITLE: 'NEWBORNS & BABIES',
  INFO_HEADER_TEXT_TITLE_TWO: 'Parenting',
  INFO_TITLE_ONE: 'Baby Care 101',
  INFO_SUBTITLE_ONE:
    'Dr. Harver Karp, Dr. Delaney Gracy, Corky Harvey IBCLC and more',
  INFO_TITLE_TWO: 'Caring For Your Newborn',
  INFO_SUBTITLE_TWO: 'Dr. Sema Hart and Prof. Jim Coffey',
  INFO_TITLE_THREE: 'Caring For Your Newborn',
  INFO_SUBTITLE_THREE: 'Dr, Glenn I.Latham, Utah State University',
  INFO_HEADER_FREE: 'FREE',
  DOWN_PAN_MENU:
    "\t \t \t DROP US A LINE AND TELL US\n  WHAT YOU'D LIKE TO LEARN ABOUT",
  MAIL_SUBJECT: 'Message from React Native App',
  MAIL_BODY:
    'Lorem Ipsum is simply dummy text of the printing and typesetting industry.Author: Emin Zeynalov',
  NEED_TO_FILL: 'Нужно заполнить поля!',
  NOT_CORRECT: 'Логин или пароль не верны!',
  NOT_MUTCH: 'Пароли не совподают!',
  MOVIE_SCREEN_IMG_TITLE:
    'Dr. Harvey Karp, Dr. Delaney Gracy, Corky Harvey IBCLC and more',
  MOVIE_SCREEN_IMG_TITLE_TWO: 'Dr. Sema Hart and Prof. Jim Coffey',
  COURSE_DESCRIPTION: 'Course description',

  CURRICULUM: 'Curiculum',
  LECTURES: '23 lectures, 1.6 hours of content',
  SEC_TIME: 'Video 2:12',

  SECTIONS_ONE: 'SECTION 1: NEWBORN BASICS',
  SECTIONS_TWO: 'SECTION 2: HOW TO CALM A BABY',
  SECTIONS_THREE: 'SECTION 3: BREASTFEEDING',
  SECTIONS_FOUR: 'SECTION 4: SLEEP SAFETY',
  SECTIONS_FIVE: 'SECTION 5: HOME SAFETY',
  SECTIONS_SIX: 'SECTION 6: CAR SAFETY',
  SECTIONS_SEVEN: 'SECTION 7: MEDICAL ISSUES',

  SEC_ONE_TITLE_ONE: 'How to wash your baby',
  SEC_ONE_TITLE_TWO: 'How to change a diaper',
  SEC_ONE_TITLE_THREE: 'Tummy time: How and when to do it',
  SEC_ONE_TITLE_FOUR: 'Ways to hold a baby',

  SEC_TWO_TITLE_ONE: 'Swaddling techniques',
  SEC_TWO_TITLE_TWO: 'How to calm a crying baby #1',
  SEC_TWO_TITLE_THREE: 'How to calm a crying baby #2',

  SEC_THREE_TITLE_ONE: 'Successful latching on',
  SEC_THREE_TITLE_TWO: 'Pumping basic',

  SEC_FOUR_TITLE_ONE: 'Creating a safe sleep environment',

  SEC_FIVE_TITLE_ONE: 'Protection from toxins ad home 1',
  SEC_FIVE_TITLE_TWO: 'Protection from toxins ad home 2',

  SEC_SIX_TITLE_ONE: 'Car seats: How to secure your newborn',
  SEC_SIX_TITLE_TWO: 'Hidden dangers of puffy coats in car',

  SEC_SEVEN_TITLE_ONE: 'What are flu symptoms?',
  SEC_SEVEN_TITLE_TWO: 'Infant allergies',
  SEC_SEVEN_TITLE_THREE: 'Baby sunburn treatment',
  SEC_SEVEN_TITLE_FOUR: 'How to treat bug bites',
  SEC_SEVEN_TITLE_FIVE: 'How to treat cuts',
  SEC_SEVEN_TITLE_SIX: 'Baby accidents',
  SEC_SEVEN_TITLE_SEVEN: 'What is Shaken Baby Syndrome?',
  SEC_SEVEN_TITLE_EIGHT: 'Finding a doctor for your baby',
  APP_NOT_INSTALLED: 'Play Market не установлен или отключен!',

  //Big Text
  SHOW_MORE_TEXT:
    "In this course you will learn the important A basics that are so mystifying for new parents: bathing and changing your baby, tips on breastfeeding, how to calm your baby and help them sleep, sleep safety, home safety and car safety, and knowing when to call the doctor. A hand-picked, all-in-one introduction to Newborn Basics, with the best and most experienced teachers, all of them certified medical professionals. Newborn basics Get excellent tips to assist you with your baby's bath time, changing a diaper, and how and when to do tummy time, and a variety of ways to safely and comfortably hold a baby. Learn all this with the qualified staff at Epworth Freemasons hospital (Victoria, Australia) and Sunnybrook Hospital (Toronto, Canada). How to Calm a Baby Newborns cry a lot, and this is normal! They are simply getting used to life outside the womb. As parents, our job is to learn the way to calm them during their first few months. Watch Dr. Harvey Karp — one of America's most widely known pediatricians - explaining his 5 S's technique for calming crying babies: Swaddle, Side-Stomach Position, Shush, Swing and Suck. Breastfeeding Learn how to breastfeed successfully from breastfeeding expert Corky Harvey, the co-founder of Pump Station & Nurture of Hollywood, CA. Learn how to master the latching technique crucial for comfortable breastfeeding, as well as how to prevent common breastfeeding issues. A safe sleep environment is crucial for your newborn. Dr. Andrew Eisen from Touro University and his colleagues from Southern Nevada Health District explain how to create a safe sleep environment according to The American Academy of Pediatrics. Home Safety How can you make your home safe for your children? In this informative video, Olivia Newton-John and Kelly Preston discuss issues concerning toxins in your home. Speaking from their own experiences as mothers and Board members of Children's Health Environmental Coalition, Olivia and Kelly offer simple you can take to make your home safer for your children and your family. Car Safety Traveling in the car with your baby requires extra safety precautions. In this series, Dr. Alisa Baer, pediatrician and child car safety expert, explains important car safety rules, including correct car seat setup, the safe sitting position for your baby, appropriate clothing for a baby buckled into a car seat, the correct way to buckle your baby and finally, safe swaddling in the car seat. edical Issues atch Dr. Delaney Gracy from Children's Health Fund explaining how to treat some of the common medical issues you might encounter with your baby, such as flu, sunburn, bug bites and allergies.",

  //New Version RU
  FULL_VERSION: 'ПОЛНАЯ ВЕРСИЯ',
  TITLE: 'Подарите всей семье дрогоценные часы хорошего сна!',
  WHATS_INSIDE: 'Что внутри:',
  OPT_1: '- Неограниченное проигрывание.',
  OPT_2: '- Неограниченный "ночной режим".',
  OPT_3: '- Отслеживание сна всю ночь.',
  BTN_1: 'ДОСТУП НА ОДИН МЕСЯЦ \n \t \t \t \t \t ЗА 189.00 Руб.',
  BTN_2: 'ДОСТУП НА ШЕСТЬ МЕСЯЦЕЦ \n \t \t \t \t \t \t \t ЗА 429.00 Руб.',
  BTN_3:
    'НЕОГРАНИЧЕННЫЙ ДОСТУП РАЗОВЫЙ \n \t \t \t \t \t \t \t ПЛАТЕЖ - 1 090.00 Руб.',
  //New Version EN
  // FULL_VERSION: 'FULL VERSION',
  // WHATS_INSIDE: "What's inside",
  // OPT_1: '- Unlimited sound duration',
  // OPT_2: '- Unlimited "Listen" mode',
  // OPT_3: '- All-nigth Sleep Tracking',
  // OPT_4: '- Extra Long Fade-Out (up to two hours)',
  // OPT_5:
  //   '- Premium audio content, including lullabies and instrumental soundtracks',
};
